server:
  port: 8080
spring:
  application:
    name: order
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://10.10.11.15:3306/ddd-order?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 200
      max-wait: 30000
      initial-size: 5
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-while-idle: true
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 300000
  # graylog
mybatis:
  mapper-locations: classpath:mapper/*.xml